#!/bin/sh

gitroot() {
  if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    echo `pwd`/`git rev-parse --show-cdup`
  fi
}

rootpath=`gitroot`
runscript="${rootpath}proj_precommit_setting/get_diff_files.rb"

ruby ${runscript}
